# Generated by Django 4.1.3 on 2022-12-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_html', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=700)),
                ('price', models.FloatField(default=0, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('status_1', models.BooleanField(default=False)),
                ('status_2', models.BooleanField(default=False)),
                ('status_3', models.BooleanField(default=False)),
                ('status_4', models.BooleanField(default=False)),
                ('status_5', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
