# Generated by Django 4.1.3 on 2022-12-13 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cords',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
