# Generated by Django 4.1.3 on 2022-12-16 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_cords'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_cords',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sensor_1_depth',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sensor_1_waypoins',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
