# Generated by Django 4.1.3 on 2022-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_custom_cords_order_sensor_1_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords',
            field=models.TextField(blank=True),
        ),
    ]
