# Generated by Django 4.1.3 on 2022-12-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_cords_alter_order_custom_cords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cords',
            new_name='route_cords',
        ),
    ]
