# Generated by Django 4.1.3 on 2022-12-27 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sensor_1_depth',
            new_name='waypoint_1_sensor_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sensor_1_waypoins',
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_1_sensor',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_1_sensor_depth',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
