# Generated by Django 4.1.3 on 2022-12-30 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_custom_cords_order_custom_cords_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='interval_time',
        ),
        migrations.AddField(
            model_name='order',
            name='interval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='onetime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='onetime_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
