# Generated by Django 4.1.3 on 2022-12-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_time_order_interval_time_order_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_cords_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_10',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_6',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_7',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_8',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_cords_9',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='interval_time',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='onetime_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_10_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_10_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_10_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_1_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_1_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_1_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_2_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_2_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_2_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_3_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_3_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_3_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_4_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_4_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_4_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_5_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_5_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_5_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_6_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_6_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_6_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_7_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_7_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_7_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_8_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_8_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_8_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_9_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_9_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='waypoint_9_sensor_message',
            field=models.TextField(blank=True),
        ),
    ]
