# Generated by Django 4.1.3 on 2023-01-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_custom_cords_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='onetime_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
