# Generated by Django 4.1.3 on 2023-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_choose_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waypoint_11_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_11_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_11_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_12_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_12_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_12_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_13_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_13_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_13_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_14_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_14_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_14_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_15_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_15_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_15_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_16_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_16_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_16_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_17_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_17_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_17_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_19_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_19_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_19_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_20_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_20_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_20_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_21_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_21_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_21_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_22_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_22_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_22_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_23_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_23_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_23_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_24_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_24_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_24_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_25_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_25_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_25_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_26_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_26_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_26_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_27_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_27_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_27_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_28_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_28_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_28_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_29_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_29_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_29_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_31_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_31_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_31_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_32_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_32_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_32_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_33_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_33_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_33_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_34_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_34_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_34_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_35_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_35_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_35_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_36_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_36_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_36_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_37_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_37_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_37_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_38_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_38_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_38_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_39_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_39_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_39_sensor_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_40_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_40_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_40_sensor_message',
            field=models.TextField(blank=True),
        ),
    ]
