# Generated by Django 4.1.3 on 2023-01-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_waypoint_11_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waypoint_30_sensor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_30_sensor_depth',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint_30_sensor_message',
            field=models.TextField(blank=True),
        ),
    ]
