# Generated by Django 4.1.3 on 2022-12-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
